window.PORTFOLIO_DATA = {
  "site": {
    "name": "Marcelo Ramos | Senior Project Manager · PMO · Governance",
    "owner": "Marcelo Henrique Ramos",
    "location": "Ribeirão Preto/SP — Brasil",
    "role": "Senior Project Manager · PMO · Portfolio & Project Governance",
    "eyebrow": "PROJECT MANAGEMENT • PMO • GOVERNANCE • DIGITAL TRANSFORMATION",
    "tagline": "Liderança de projetos complexos conectando estratégia, negócio e tecnologia.",
    "subtitle": "Senior Project Manager com atuação em PMO, portfólio, governança, Agile/Scrum, PMBOK e modelos híbridos de delivery, combinando gestão executiva e profundidade em projetos de transformação digital e Microsoft Dynamics 365.",
    "linkedin": "https://www.linkedin.com/in/marcelo-ramos-245246137",
    "baseUrl": "https://marcelohr100-bit.github.io/marcelo-ramos-portfolio",
    "basePath": "/marcelo-ramos-portfolio/"
  },
  "coreExpertise": [
    {"title":"Project Management","text":"Planejamento, coordenação e acompanhamento de entregas complexas, conectando objetivos de negócio e execução."},
    {"title":"PMO & Portfolio","text":"Visão de portfólio, priorização, acompanhamento executivo e organização de governança entre iniciativas."},
    {"title":"Project Governance","text":"Ritos, critérios de decisão, rastreabilidade, indicadores e clareza de responsabilidades ao longo do delivery."},
    {"title":"Agile & Scrum","text":"Uso pragmático de práticas ágeis para cadência, transparência, inspeção e adaptação das entregas."},
    {"title":"PMBOK & Hybrid Delivery","text":"Estruturação de projetos combinando práticas preditivas e adaptativas de acordo com contexto, risco e dependências."},
    {"title":"Stakeholder Management","text":"Alinhamento entre negócio, tecnologia, liderança, times de projeto e demais partes envolvidas na entrega."},
    {"title":"Risk, Scope & Budget","text":"Gestão integrada de riscos, escopo, prioridades, impactos e acompanhamento financeiro do projeto."},
    {"title":"Team Leadership","text":"Coordenação de times multidisciplinares com clareza de objetivos, responsabilidades, impedimentos e decisões."},
    {"title":"Digital Transformation","text":"Condução de iniciativas que conectam processos, tecnologia e mudança organizacional em ambientes corporativos."}
  ],
  "projects": [
    {
      "slug":"integracao-erp-crm","name":"Integração ERP–CRM","category":"Transformação Digital","status":"Case profissional anonimizado","summary":"Case de integração entre CRM, ERP e serviços de automação para sincronizar cadastros, pedidos e regras comerciais.","role":"Project Leadership & Delivery Governance","context":"Projeto corporativo com dependências entre CRM, ERP, integrações e regras de negócio, exigindo coordenação entre diferentes frentes de entrega.","challenge":"Organizar cenários críticos de integração, reduzir ambiguidades de escopo e tornar o acompanhamento entre negócio e tecnologia mais rastreável.","governance":"Levantamento e consolidação de regras, priorização de cenários críticos, coordenação entre equipes, acompanhamento de riscos, validação em homologação e governança da implantação.","stakeholders":"Áreas de negócio, consultoria funcional, desenvolvimento e integração, arquitetura técnica e liderança do projeto.","deliverables":["Integração de produtos e novos clientes","Tratamento de pedidos não integrados","Fluxos relacionados a comissão de vendas","Testes, homologação e acompanhamento de implantação"],"outcome":"Coordenação e homologação das entregas previstas no escopo, com acompanhamento estruturado dos fluxos críticos de integração.","technologyEcosystem":["Microsoft Dynamics 365","Azure Functions","Power Automate","REST APIs"],"technologyLabel":"Technology Ecosystem","published":true
    },
    {
      "slug":"smartmenu-ai","name":"SmartMenu AI","category":"Digital Product Initiative","status":"Em desenvolvimento","summary":"Iniciativa de produto para cardápio digital, pedidos e operação de atendimento em restaurantes, estruturada como solução web.","role":"Product Strategy & Project Leadership","context":"Iniciativa própria voltada a uma experiência digital de atendimento em restaurantes sem exigir instalação de aplicativo pelo cliente final.","challenge":"Conectar experiência na mesa e operação do restaurante em um fluxo simples, priorizável e evolutivo.","governance":"Mapeamento de jornadas, definição de regras de negócio, priorização do escopo, prototipação navegável e planejamento incremental do MVP.","stakeholders":"Contexto de experiência do cliente, atendimento, cozinha e administração do restaurante como referências de discovery e operação.","deliverables":["QR Code individual por mesa","Cardápio por categorias e carrinho","Pedidos, chamada de garçom e solicitação de conta","Visões para cozinha e administração"],"outcome":"Escopo e protótipo estruturados para evolução incremental; o produto permanece em desenvolvimento.","technologyEcosystem":["Next.js","React","TypeScript","Supabase"],"technologyLabel":"Planned Technology Ecosystem","published":true
    }
  ],
  "caseFramework": ["PMO / Portfolio Governance","Complex Technology Implementation / Go-Live","Delivery Methodology Transformation","ERP–CRM Integration","Project Recovery / Risk & Quality Governance","Digital Product Initiative"],
  "method": [
    {"number":"01","title":"Alinhar","text":"Objetivos, stakeholders, escopo, contexto, restrições e critérios de sucesso."},
    {"number":"02","title":"Planejar & Governar","text":"Roadmap, riscos, dependências, responsabilidades, cadência e mecanismos de decisão."},
    {"number":"03","title":"Entregar & Validar","text":"Coordenação de times, acompanhamento executivo, testes, homologação e gestão de mudanças."},
    {"number":"04","title":"Encerrar & Evoluir","text":"Aceites, documentação, transição, lições aprendidas e evolução do modelo de delivery."}
  ],
  "products": [
    {"slug":"airclaim-vault","name":"AirClaim Vault — Flight Disruption Claim Desk","category":"Travel Operations","type":"Claim Desk","audience":"Viajantes, consultores de viagem, agências e equipes de suporte que organizam solicitações relacionadas a interrupções de voo","summary":"Pacote operacional para registrar a interrupção do voo, organizar evidências e despesas, acompanhar comunicações e manter o andamento da solicitação em um único lugar.","image":"assets/products/airclaim-vault.svg","imageAlt":"Capa ilustrativa do produto AirClaim Vault — Flight Disruption Claim Desk","purchaseLinks":[{"platform":"Gumroad","url":"https://marceloramos3.gumroad.com/l/airclaim-vault?layout=profile"},{"platform":"Payhip","url":"https://payhip.com/b/P0zhF"}],"highlights":["Intake estruturado dos dados do voo e da interrupção","Checklist para reunir documentos, comprovantes e evidências","Registro de despesas, contatos e comunicações","Acompanhamento organizado do status da solicitação"],"included":["Pacote digital AirClaim Vault","Desk e materiais operacionais descritos na oferta oficial"],"notice":"Ferramenta de organização operacional. Não garante indenização e não substitui aconselhamento jurídico ou análise individual de elegibilidade.","homeFeatured":true},
    {"slug":"battery-passport-intake-desk","name":"Battery Passport Intake Desk — Supplier Data & Evidence Workbook","category":"Sustentabilidade & Supply Chain","type":"Supplier Workbook","audience":"Fabricantes, importadores, fornecedores e equipes de compras, sustentabilidade ou compliance que precisam organizar dados para passaportes de bateria","summary":"Workbook profissional para coletar dados de fornecedores, registrar evidências, identificar lacunas e estruturar o intake necessário ao trabalho com passaportes de bateria.","image":"assets/products/battery-passport-intake-desk.svg","imageAlt":"Capa ilustrativa do produto Battery Passport Intake Desk — Supplier Data & Evidence Workbook","purchaseLinks":[{"platform":"Gumroad","url":"https://marceloramos3.gumroad.com/l/battery-passport-intake-desk?layout=profile"},{"platform":"Payhip","url":"https://payhip.com/b/krKby"}],"highlights":["Intake estruturado de dados por fornecedor","Registro de documentos e evidências associados","Identificação de lacunas, responsáveis e pendências","Base reutilizável para revisão e acompanhamento do processo"],"included":["Supplier Data & Evidence Workbook","Materiais de intake e controle descritos na oferta oficial"],"notice":"Workbook operacional de organização de dados. Não substitui validação técnica, jurídica ou regulatória especializada.","homeFeatured":true},
    {"slug":"sbom-drift-desk","name":"SBOM Drift Desk","category":"Cibersegurança","type":"Aplicação offline","audience":"Times de segurança, compliance e engenharia de software","summary":"Ferramenta local para comparar SBOMs CycloneDX e SPDX, identificar alterações e exportar evidências sem depender de servidor ou assinatura.","image":"assets/products/sbom-drift-desk.svg","imageAlt":"Capa ilustrativa do produto SBOM Drift Desk","purchaseLinks":[{"platform":"Gumroad","url":"https://marceloramos3.gumroad.com/l/sbom-drift-desk"},{"platform":"Payhip","url":"https://payhip.com/b/swb3H"}],"highlights":["Comparação de SBOMs CycloneDX e SPDX","Identificação de mudanças em componentes e versões","Processamento local e privado","Exportação de evidências para análise"],"included":["Aplicação offline para download","Materiais de utilização descritos na oferta oficial"],"notice":"","homeFeatured":true},
    {"slug":"cra-24h-incident-desk","name":"CRA 24H Incident Desk","category":"Compliance","type":"Incident Desk","audience":"Times de segurança, produto e compliance","summary":"Kit operacional para acompanhar prazos, responsáveis e evidências de incidentes relacionados ao Cyber Resilience Act.","image":"assets/products/cra-24h-incident-desk.svg","imageAlt":"Capa ilustrativa do produto CRA 24H Incident Desk","purchaseLinks":[{"platform":"Gumroad","url":"https://marceloramos3.gumroad.com/l/cra-24h-incident-desk"},{"platform":"Payhip","url":"https://payhip.com/b/VuNvf"}],"highlights":["Organização dos marcos de 24 e 72 horas","Controle de responsáveis e contatos","Centralização das evidências","Preparação consistente dos pacotes de reporte"],"included":["Pacote digital CRA 24H Incident Desk","Modelos operacionais descritos na oferta oficial"],"notice":"Ferramenta operacional. Não substitui aconselhamento jurídico ou regulatório especializado.","homeFeatured":false},
    {"slug":"a50-agency-desk","name":"A50 Agency Desk","category":"AI Governance","type":"Compliance Kit","audience":"Agências, freelancers e criadores que utilizam IA em trabalhos destinados ao mercado europeu","summary":"Kit local para documentar o uso de IA, organizar aprovações e aplicar avisos de transparência em trabalhos criativos e de marketing.","image":"assets/products/a50-agency-desk.svg","imageAlt":"Capa ilustrativa do produto A50 Agency Desk","purchaseLinks":[{"platform":"Gumroad","url":"https://marceloramos3.gumroad.com/l/a50-agency-desk"},{"platform":"Payhip","url":"https://payhip.com/b/VJ7qZ"}],"highlights":["Registro do uso de conteúdo gerado ou manipulado por IA","Biblioteca de avisos para adaptação","Fluxo de aprovação do cliente","Processo local, reutilizável e organizado"],"included":["Pacote digital A50 Agency Desk","Modelos e materiais descritos na oferta oficial"],"notice":"Kit operacional de transparência. Não substitui aconselhamento jurídico.","homeFeatured":false},
    {"slug":"90-second-shield","name":"90 Second Shield","category":"Bem-estar","type":"Guia digital","audience":"Pessoas que buscam uma preparação rápida para situações de ansiedade social","summary":"Guia prático e discreto com uma rotina curta para organizar respiração, foco e próximos passos antes de interações sociais desafiadoras.","image":"assets/products/90-second-shield.svg","imageAlt":"Capa ilustrativa do produto 90 Second Shield","purchaseLinks":[{"platform":"Gumroad","url":"https://marceloramos3.gumroad.com/l/90-second-shield"},{"platform":"Payhip","url":"https://payhip.com/b/aGNJF"}],"highlights":["Rotina estruturada para consulta rápida","Passos curtos e acionáveis","Uso individual e discreto","Compra disponível no Gumroad e na Payhip"],"included":["Guia digital 90 Second Shield","Instruções de uso disponibilizadas na oferta oficial"],"notice":"Material educacional de apoio pessoal. Não substitui terapia, diagnóstico ou acompanhamento profissional.","homeFeatured":false}
  ],
  "profile": {
    "intro":"Atuo na liderança de projetos de tecnologia conectando estratégia, negócio e execução. Minha abordagem combina governança, organização de portfólio, gestão de stakeholders, riscos, escopo, orçamento e modelos de delivery adaptados ao contexto de cada iniciativa.",
    "aboutOpening":"Projetos complexos exigem mais do que acompanhamento de cronograma. Exigem governança, pessoas, método e capacidade de decisão.",
    "education":["Bacharelado em Ciência da Computação","MBA em Gestão de Projetos com Metodologias Ágeis","Pós-graduação em Gestão de Projetos de Cloud Computing"],
    "tools":["Dynamics 365","Azure","Power Platform","Azure DevOps","Jira","Microsoft Project","Figma","Power BI"],
    "certifications":[
      {"name":"Certificate Professional Google Project Management","issuer":"Google","issued":"fev. 2024","group":"Gestão e liderança"},
      {"name":"Agile Scrum Master","issuer":"Fundação Vanzolini","issued":"mar. 2023","group":"Gestão e liderança"},
      {"name":"Certificação em Liderança","issuer":"PUCRS","issued":"ago. 2021","group":"Gestão e liderança"},
      {"name":"Gestão de Projetos e MS Project","issuer":"Udemy","issued":"out. 2020","group":"Gestão e liderança"},
      {"name":"Gestão de Projetos","issuer":"Fundação Bradesco","issued":"nov. 2018","group":"Gestão e liderança"},
      {"name":"Coypu: Automação Web de ponta a ponta com .NETCore","issuer":"QAninja Academy","issued":"ago. 2020","group":"Tecnologia e qualidade"},
      {"name":"UI & UX DESIGN com Adobe XD 2021","issuer":"Udemy","issued":"mar. 2020","group":"Tecnologia e qualidade"},
      {"name":"Linguagem de programação C#","issuer":"Fundação Bradesco","issued":"out. 2018","group":"Tecnologia e qualidade"},
      {"name":"C++ Desenvolvimento Orientado a Objetos","issuer":"Fundação Bradesco","issued":"out. 2018","group":"Tecnologia e qualidade"},
      {"name":"Certified Ethical Hacking","issuer":"Udemy","issued":"ago. 2017","group":"Tecnologia e qualidade"}
    ],
    "recommendationCount":5,
    "recommendations":[
      {"author":"Bruno Iwamoto Bergamini, MSc.","summary":"Destaca dinamismo, busca contínua por melhorias nos processos e capacidade de exercer uma liderança eficiente mesmo diante de desafios."},
      {"author":"Lilian Tavares","summary":"Ressalta domínio de metodologias, boas estratégias para os projetos e disposição para apoiar o desenvolvimento e a adaptação de colegas."}
    ]
  }
};
